### ISSUE TITLE
Using setInAppMessagesVisible(false) with tap on push notifications

### ISSUE THREAD

**Issue by alessandroorru** [intercom/intercom-ios#190] opened 2016-10-28 16:54 UTC
Not 100% sure if this is a bug, but for sure documentation isn't clear on this point, so here it is.

My app needs a secure session, so each time users open it they need to unlock the app with a passcode, and I'd like to keep safe also to answer to an Intercom conversation. 
The problem is that when I tap on an Intercom push notification and the app is in background, the app opens in the unlock screen, *but* the message window appears over it. I would like to keep it closed until the user unlocks the app, so I tried to relay on `setInAppMessagesVisible(false)`, but it seems to only affect the behavior when a message is received while I'm actively using the app.

Using `reset` also disables the push notifications, so I can't use it. The only workaround I found is to listen to the `IntercomWindowDidShowNotification` and manually close the messenger, but it is an ugly hack. 

## Version info
  - Intercom for iOS version: 3.0.17
  - iOS version: tried on iOS 9 and 10

## Expected behavior
If the app is in background and a user taps on an incoming push notification, I expect that no Intercom window appears, if I previously used `setInAppMessagesVisible(false)`

## Actual behavior
When the app opens, I get the Intercom conversation

## Steps to reproduce
 1. Use `setInAppMessagesVisible(false)`
 2. Put the app in background
 3. Receive a push notification in-app message
 4. Tap on it

**Comment by bboyle18** [comment] 2016-10-28 17:29
Hi @alessandroorru 👋

Thanks for getting in touch. 
This is expected behaviour, the method setInAppMessagesVisible(false) doesn't have an impact on push notifications. 

From your description, it sounds like you want to intercept the handling of an Intercom push notification and not display the messenger window if your app is locked. 
If this is the case then there's currently no way to do it because we automatically handle Intercom push notifications by safely swizzling your code. 

The good news is though that we are working on a new feature in the SDK that will allow you to manually handle Intercom push notifications. This should allow you to intercept them for your requirements. This will be released in a new version of the SDK in the next week or so. 🎉

Hopefully this will help address the issue you're facing. If not, or if you have any further questions feel free to get back to us. 

Cheers

Brian

**Closed by bboyle18** 2016-10-28 17:29 UTC

**Comment by alessandroorru** [comment] 2016-10-28 17:46
@bboyle18 perfect, thank you!
