### ISSUE TITLE
- [PodIntercom__SRRunLoopThread main] Crash

### ISSUE THREAD

**Issue by iCyberon** [intercom/intercom-ios#125] opened 2016-03-12 08:11 UTC
Recently I've received Intercom crashes in Fabric.

## Version info
  - Intercom for iOS version: 2.3.19
  - iOS version: 7.1.2

## Expected behavior
To not crash

## Actual behavior
Crashes

## Steps to reproduce
Have no idea.

## Logs
```
Thread : Crashed: Thread
0  libsystem_platform.dylib       0x39bc7a32 spin_lock$VARIANT$up + 1
1  CoreFoundation                 0x2ed836d7 CFSocketEnableCallBacks + 54
2  CFNetwork                      0x2e9e2311 SocketStream::securityBufferedRead_NoLock() + 212
3  CFNetwork                      0x2e9e220d SocketStream::socketCallbackReadLocked(SocketStreamSignalHolder*) + 68
4  CFNetwork                      0x2e9e09df SocketStream::socketCallback(__CFSocket*, unsigned long, __CFData const*, void const*) + 102
5  CFNetwork                      0x2e9e0947 SocketStream::_SocketCallBack_stream(__CFSocket*, unsigned long, __CFData const*, void const*, void*) + 58
6  CoreFoundation                 0x2edc03c3 __CFSocketPerformV0 + 578
7  CoreFoundation                 0x2edbe20b __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 14
```

**Comment by ronocod** [comment] 2016-03-12 11:30
Hi @iCyberon,

Thanks for reporting this, could you give us a link to the crashes like in [this comment](https://github.com/intercom/intercom-ios/issues/124#issuecomment-193444290)?

This looks like it's related to SocketRocket, and possibly https://github.com/intercom/intercom-ios/issues/124 too. We're looking into fixing these issues, and we'll add an update here whenever we find something out.

**Comment by DaleCantwell** [comment] 2016-04-14 09:16
Going to close this one as a duplicate of #124 
Thanks again for letting us know about the issue, I will copy your crash log over to that issue.

**Closed by DaleCantwell** 2016-04-14 09:16 UTC
Labels: duplicate
