### ISSUE TITLE
presentMessageComposer - Something went wrong

### ISSUE THREAD

**Issue by sammy-SC** [intercom/intercom-ios#198] opened 2016-11-24 11:34 UTC
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.0.18 and 3.0.19
  - iOS version: 10.1.1

## Expected behavior
To start conversation over intercom.

## Actual behavior
Presents following error to the user
![img_0240](https://cloud.githubusercontent.com/assets/1733610/20596978/74559b00-b241-11e6-89b4-c32a72aa5c36.PNG)

## Steps to reproduce
This happens when the app is freshly installed and `Intercom.presentMessageComposer()` is called.
`Intercom.registerUser(withUserId: userId)` is called before .

When i kill the app and relaunch it, `Intercom.presentMessageComposer()` works fine.

## Logs
I didn't find anything relevant being logged in the console.

Thanks

**Comment by jtreanor** [comment] 2016-11-24 11:40
Hi @sammy-SC,

Can you try calling `Intercom.enableLogging()` and let us know if you see anything in the logs after going through the steps again.

Is this reproducible every time you follow the steps?

**Comment by sammy-SC** [comment] 2016-11-24 13:17
Hello @jtreanor,

thank you for quick answer.

I called `Intercom.enableLogging()` but it didn't produce any console output.

Yes, this issue happens every single time i have a fresh install.

**Comment by jtreanor** [comment] 2016-11-24 14:43
On the fresh install, when do you call `Intercom.registerUser(withUserId: userId)`. Is it when the user logs in?

**Comment by sammy-SC** [comment] 2016-11-24 15:35
@jtreanor yes, it is exactly when user logs in.

**Comment by jtreanor** [comment] 2016-11-24 15:51
Is it possible that `userId` is not set at this point. If it is nil that could silently fail.

**Comment by sammy-SC** [comment] 2016-11-24 16:12
@jtreanor i do check whether `userId` is not nil before i call `Intercom.registerUser(withUserId: userId)`, so `usedId` is always a valid string.

**Comment by jtreanor** [comment] 2016-11-24 16:31
Thanks @sammy-SC. Can you put a breakpoint on the `registerUser` line on login to make sure it is getting called?

**Comment by sammy-SC** [comment] 2016-11-24 19:51
@jtreanor I did that, I am sure it is getting called.
I also made sure I do not call `Intercom.reset`.

**Comment by jtreanor** [comment] 2016-11-24 22:18
Thanks for the detail. Could you contact us via the Messenger on Intercom.com? It will be easier to resolve your issue there

**Comment by famanson** [comment] 2016-12-13 11:36
@jtreanor hiya, what is the progress on this issue?

**Comment by jtreanor** [comment] 2016-12-13 11:46
Hi @famanson,

This issue appears to be specific to this integration. If you would like help will getting Intercom set up feel free to message us via the messenger on http://www.intercom.com. If you believe you are seeing an issue, let us know.

**Comment by jtreanor** [comment] 2017-01-04 10:53
Closing as this appears to have been an issue specific to this integration. If you believe this is not the case, feel free to reopen the issue.

**Closed by jtreanor** 2017-01-04 10:53 UTC

**Comment by famanson** [comment] 2017-01-20 10:23
Hi, sorry for the late late response. I've been busy resolving an issue on our side with a data loss (incidentally... from Intercom as well). This is still an issue for us, and given the latest Intercom incident that we had, I think this might be related.

- The first issue we had (for about 2 months) was a massive user data loss, and this was because the backend failed to match unidentified and identified users.
- This SDK issue was reported on the 24th Nov, which is the exact date as the above data loss happened (correlation here?)
- Even after we were _told_ the issue was fixed (emphasis on _told_ since our data is still not recovered yet), some user data still took about 15 minutes to be properly matched. All the users with the problem in this ticket are new signups, so I think there is a very high probability that this is related. Could you please take a closer look at this again on your end?
- We register unidentified user when they open the app, and register the user ID when they sign up or sign in. Is this the correct way to do it via the SDK?
