### ISSUE TITLE
Terrible Clone Times in Jenkins CI: repo size is 450+ MB

### ISSUE THREAD

**Issue by timshadel** [intercom/intercom-ios#191] opened 2016-10-28 21:08 UTC
## Version info
- Intercom for iOS version: Any
- iOS version: Any
## Expected behavior

My Jenkins instance that creates a new workspace for each branch should be able to download all submodules cleanly and quickly on first build of that branch (this involves a fresh clone of `intercom-ios`).
## Actual behavior

Builds always get stuck cloning `intercom-ios`, many for 30+ minutes. This clogs up the build machine for all other apps that need to be built on it.
## Steps to reproduce

Open the [repo details api for `intercom-ios`](https://api.github.com/repos/intercom/intercom-ios) and look at `size` (KB) and notice that the entire repo (with history) is 450+ MB.
## Logs

N/A
## Workarounds Attempted

Shallow cloning of submodules is difficult. The submodule points at both a repo (for clone) and a commit hash (for checkout). As the repo advances, there's no way to know how far back in the history to clone shallowly in order to get the version that you're pinned to. We've tried about 3 different methods of shallow cloning submodules to workaround this.

We use Carthage, and have many Swift 3 dependencies. Because Swift's ABI is not stable, this means that we manage all dependencies via submodules (`carthage bootstrap --no-build --use-submodules`). It works incredibly well for us. It's [not currently possible to mix](https://github.com/Carthage/Carthage/issues/1020) some dependencies as submodules and some not.
## Core problem

You're checking in all the binaries for the framework. Each version has 40+ MB in binaries.

``` sh
$ find . -type f | grep -v objects | xargs du -h | gsort -h

 24K    ./Examples/Sample-Swift/Sample-Swift/Assets.xcassets/Intercom-logo.imageset/Intercom-logo@3x.png
7.8M    ./Intercom.framework.dSYM/Contents/Resources/DWARF/Intercom
 35M    ./Intercom.framework/Intercom
```

This leads to a possibly simple approach to fixing this, with one major question mark.
## Approach that I'd like you to investigate

Use Github's [Large File Support](https://github.com/github/git-lfs) to make sure that all files named `Intercom` are treated as large.

This would ensure that the actual repo wouldn't bloat with every subsequent release, and still allow you to treat the entire binary as part of the repo.
### The complication

You'll need to rewrite your entire repository history using `git filter-branch` or `bfg` to [remove the existing binaries](https://github.com/github/git-lfs/issues/326) and re-add them as LFS to shrink the repo size. That'd mean changing all the SHAs for all your existing releases. That'd break everybody once. That stinks, but it's almost a necessary evil for future kindness to your users given the rate at which you guys release (which is awesome, btw).

**Comment by jtreanor** [comment] 2016-11-01 12:31
Hi @timshadel,

Thanks for the detailed and thoughtful report.

Your use case is an interesting one. Usually Carthage consumes the Github release only and so does not clone the repo. https://github.com/Carthage/Carthage/issues/1020 complicates this somewhat. Every other install type does not require cloning.

However, your concerns are completely valid. The repo is much too large. We'll dig into your suggestion and other possible approaches to see how we can tackle it.

I'll keep you updated,
James

**Comment by jtreanor** [comment] 2016-11-03 17:27
I have done some more research here and unfortunately, Github's Large File Support will not be an appropriate solution to this problem. The reason for this is that everyone who clones the repo (or installs older versions via CocoaPods) would need to have `git-lfs` installed.

An alternative solution could be to stop storing binaries in the repo altogether. We already distribute various binaries via [Github Releases](https://github.com/intercom/intercom-ios/releases) and could extend our usage.
However, your submodule use case would break if we did this.

**Comment by kafejo** [comment] 2016-11-19 14:35
Another possible workaround using Cocoapods is to create podspec only repository and use it as a source. 

Example:
add source on top of the Podfile
```
source 'https://github.com/kafejo/intercom-podpec'
```
and run `pod install`.

**Comment by jtreanor** [comment] 2016-11-21 10:52
@kafejo There are no known issues with the CocoaPods setup so this won't resolve the issue here.

The problem is that @timshadel's configuration means the git repo is cloned on every build. The podspec already does not clone the git repo.

**Comment by bboyle18** [comment] 2017-01-16 15:19
Closing this as there is not much we can do to cater for this specific build configuration.

**Closed by bboyle18** 2017-01-16 15:19 UTC

**Comment by mossby** [comment] 2017-11-21 20:37
Just want to throw out there that I am now facing this same problem. A little frustrating since other frameworks that I would consider to be "very large and complex" like Realm and Alamofire clone very quickly, but Intercom takes so long I get timed out by Travis every single time. Maybe Intercom has more going on than I realize, but something def feels off about that assessment.

**Comment by jtreanor** [comment] 2017-11-21 20:46
Thanks @mossby

Just to be clear, how are you installing Intercom? There should be very little need to clone the repo.

**Comment by kafejo** [comment] 2017-11-21 21:00
@jtreanor If I'm not mistaken, git clone is being called when installing via Cocoapods.

**Comment by jtreanor** [comment] 2017-11-21 21:03
@kafejo What version are you using. Since 3.0.0 the podspec for Intercom does not clone the git repo. Latest version is 4.1.3.

**Comment by kafejo** [comment] 2017-11-22 07:01
We have latest version and don't experience the issue anymore. Just saying that it might be the case for someone else. 🙂

**Comment by mossby** [comment] 2017-11-22 15:54
Heya, thanks for responding back. I was using Carthage, which may be the reason I was experiencing the issues I was. Also using the latest version of Intercom (4.1.3)

I def tried everything in my Travis script from `update` to `bootstrap` to every combination of flags (`--no-use-binaries`, etc) I could think of 😄 

I ultimately ended up embedding the Intercom framework directly in my app, and things are working now. (No the Travis build still isn't successful, but for other reasons now lol)

So perhaps it is just an issue with Carthage? Maybe there is something to look into there on y'alls end? Not the biggest fan of Cocoapods tbh

**Comment by jtreanor** [comment] 2017-11-22 16:21
Thanks for your response @mossby. Carthage should not be cloning the git repo, as Intercom is provided as a binary through Github Releases. See `Carthage.zip` [here](https://github.com/intercom/intercom-ios/releases). I will look into anything else that could be causing a slow down here.

Glad you are unblocked 😄

**Comment by mossby** [comment] 2017-11-22 16:25
Interesting, I will say that other frameworks were pulling the prebuilt binaries for me, but for some reason Intercom was not. I'll go thru my setup again and see if there is something weird I'm doing. Using fastlane (and Travis) for the first time so lots for me to potentially mangle 😂 Thanks again @jtreanor
