### ISSUE TITLE
Crash in ICMReactionsViewController

### ISSUE THREAD

**Issue by allu22** [intercom/intercom-ios#224] opened 2017-02-09 15:29 UTC
Hi, we have seen 2 crashes from Intercom framework.

## Version info
  - Intercom for iOS version: 3.0.20
  - iOS version: 9.2.1, 9.3.0
  - Device: iPhone 5s

## Expected behavior
App would not crash

## Actual behavior
App crashes

## Steps to reproduce
Not known.

## Logs

```
Fatal Exception: NSRangeException
0  CoreFoundation                 0x183ca2e38 __exceptionPreprocess
1  libobjc.A.dylib                0x183307f80 objc_exception_throw
2  CoreFoundation                 0x183b82ebc -[__NSArrayM removeObjectAtIndex:]
3  MyAppl                         0x100769b80 -[ICMReactionsViewController didPan:]
4  UIKit                          0x18937dc8c _UIGestureRecognizerSendTargetActions
5  UIKit                          0x188f925dc _UIGestureRecognizerSendActions
6  UIKit                          0x188e1f688 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:]
7  UIKit                          0x18937f28c ___UIGestureRecognizerUpdate_block_invoke898
8  UIKit                          0x188dde3d8 _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks
9  UIKit                          0x188ddb154 _UIGestureRecognizerUpdate
10 UIKit                          0x188e1d4f8 -[UIWindow _sendGesturesForEvent:]
11 UIKit                          0x188e1caf4 -[UIWindow sendEvent:]
12 UIKit                          0x188decf4c -[UIApplication sendEvent:]
13 UIKit                          0x188deb528 _UIApplicationHandleEventQueue
14 CoreFoundation                 0x183c59124 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
15 CoreFoundation                 0x183c58bb8 __CFRunLoopDoSources0
16 CoreFoundation                 0x183c568b8 __CFRunLoopRun
17 CoreFoundation                 0x183b80d10 CFRunLoopRunSpecific
18 GraphicsServices               0x185468088 GSEventRunModal
19 UIKit                          0x188e55f70 UIApplicationMain
20 MyAppl                         0x1000f1614 main (AppDelegate.swift:17)
21 libdispatch.dylib              0x18371e8b8 (Missing)
```

**Comment by bboyle18** [comment] 2017-02-09 15:33
Hi @allu22 👋 
Thanks for reporting this. We haven't seen this before so we'll investigate and provide an update here when we have fixed it.

Thanks!

Brian

**Comment by allu22** [comment] 2017-02-13 08:42
Hi @bboyle18 

we have seen this crash only from 2 of our users.

Alvar

**Comment by bboyle18** [comment] 2017-02-13 10:11
Thanks @allu22 
We'll look at getting a fix for this in our next release
Brian

**Comment by bboyle18** [comment] 2017-03-08 17:54
Unable to reproduce this. The issue happened twice in version 3.0.20. This area of code has since been updated. Anyone getting the same error should update to the latest version.
Brian

**Closed by bboyle18** 2017-03-08 17:54 UTC
