### ISSUE TITLE
Openning a push notication message , can not control message view. 

### ISSUE THREAD

**Issue by aybarsyalcin** [intercom/intercom-ios#157] opened 2016-07-31 11:00 UTC
When the application is close or background mode, one notification fires on notifcations menu. then click it. then openning the application. 
## Version info
  - Intercom for iOS version: 3.0.4
  - iOS version: 9.3.1

## Expected behavior
first view controller appears on screen. all views are loaded. then if there is unread message on intercom, the message view opens by intercom api. 
## Actual behavior
during openning app on splash view, firstly, if there is unread message,the message view opens. then at the same time my system logins and firstview controller sets on window.rootviewcontroller , so the message view hides mesage view. 

## Steps to reproduces
1. more control open/hide the message view by developer.

**Comment by jtreanor** [comment] 2016-08-02 12:27
@aybarsyalcin Can you clarify what the issue is here?
Is this a feature request or are you seeing issues with Intercom when opening push notifications?

**Comment by jtreanor** [comment] 2016-08-08 15:36
@aybarsyalcin I am closing this as it seems to be a feature request.

If you wish to respond in certain ways to psuh notifications, you may want to use a push only message: https://docs.intercom.io/intercom-s-key-features-explained/how-do-mobile-push-notifications-work-with-intercom.

Feel free to reopen if I am mistaken and you are seeing an issue with Intercom.

**Closed by jtreanor** 2016-08-08 15:36 UTC

**Comment by hydr93** [comment] 2016-08-21 15:07
@jtreanor I am also struggling the same problem and I want to rephrase the problem. When an in-app message with push notification is sent from "app.intercom.io" and my application is closed, when the user opens the application via notification (from lock screen or home screen), this issue happens. 

Since an ios application can set the first view controller from the AppDelegate, the model view controller of intercom chat opens and closes directly. I have also tried not to set the first view controller when the application is opened via notification, however "UIApplicationLaunchOptionsLocalNotificationKey" value of "launchOptions" is always null. 

I think that the main problem here is probably the "swizzling" method you are using.

**Comment by jtreanor** [comment] 2016-08-29 13:38
@hydr93 Apologies for the delay responding here.
I don't quite understand the issue you are having.

When you open the notification, does Intercom open correctly? It is expected to and `UIApplicationLaunchOptionsLocalNotificationKey` is expected to be absent.

Have you tried using the push messages I linked above?
