### ISSUE TITLE
No such module Intercom with swift

### ISSUE THREAD

**Issue by lowki93** [intercom/intercom-ios#136] opened 2016-05-27 08:53 UTC
I use pod to install Intercom.
When i'm build my project i have : No such module Intercom.

I use swift 2.2 and pod 1.0.0

**Comment by jtreanor** [comment] 2016-05-27 09:11
Hi @lowki93,

Thanks for letting us know. What version of Intercom for iOS are you using?

**Comment by lowki93** [comment] 2016-05-27 09:12
the lastest: 2.3.21
It's this version in your podspec.

**Comment by jtreanor** [comment] 2016-05-27 09:13
Thanks @lowki93,

I'll look into this right away.

**Comment by lowki93** [comment] 2016-05-27 09:16
thanks

**Comment by jtreanor** [comment] 2016-05-27 09:31
I have done the following, but so far have been unable to reproduce the error you are seeing:

1. Create new Swift project in Xcode.
2. Add a `Podfile` with Intercom.
3. Run `pod install` using CocoaPods 1.0.0.
4. Open the `.xcworkspace` file.
5. Add `import Intercom` and `Intercom.setApiKey("api_key", forAppId: "app_id")` to my AppDelegate.
6. Build & run.

My `Podfile` contents are:

```
target 'SwiftPodTest' do
  pod 'Intercom'
end
```

@lowki93 Can you give some more info about you app the error you are seeing?

**Comment by dotmartyr** [comment] 2016-06-10 22:12
@lowki93  Were you able to fix this issue? I am experiencing the same thing after updating CocoaPods from 0.39 -> 1.0.1

**Comment by jtreanor** [comment] 2016-06-14 12:07
@dotmartyr Do you have any more details about the error you are seeing?
Is it possible there is an issue with your CocoaPods installation?

**Comment by dotmartyr** [comment] 2016-06-14 15:47
Yes, @jtreanor it was a cocoapods issue.

**Comment by jtreanor** [comment] 2016-06-14 16:46
Thanks @dotmartyr,

I'll close this issue.

**Closed by jtreanor** 2016-06-14 16:46 UTC

**Comment by cayde-6** [comment] 2017-08-28 09:32
Hello, I have similar issue with 4.0.0 version.
v3.2.12 - All is good
When I "import Intercom" in *.swift file in the objc project
