### ISSUE TITLE
Message field disappears after open-closing an image on iOS 8.x

### ISSUE THREAD

**Issue by narekam** [intercom/intercom-ios#209] opened 2017-01-19 08:42 UTC
## Version info
  - Intercom for iOS version: 3.0.15
  - iOS version: 8.x

## Expected behavior
Message field should show up

## Actual behavior
No message field showed up

## Steps to reproduce
See the GIF

![no message field](https://cloud.githubusercontent.com/assets/13750851/22099377/8d2985d6-de44-11e6-9698-cfae99b5404f.gif)

**Comment by bboyle18** [comment] 2017-01-19 08:48
Hi @narekam 👋

Thanks for reporting this issue. 
We're in the process of fixing this at the moment, but it would be great to get a little more info from you. 

Would you be able to message us on http://Intercom.com and get some more details about your app there? It will really help me diagnose what's going on 👍🏻

Thanks

Brian

**Comment by narekam** [comment] 2017-01-19 09:17
@bboyle18 thanks for quick response!
What kind of info you need? I will update an issue right here

**Comment by bboyle18** [comment] 2017-01-19 09:20
No problem!
Heres a couple of bits of info that will help 😄 

1. Can you share your podfile or a list of the 3rd party apps you are using in the app?
2. What is the name of the app? Can I download it from the AppStore and use it myself?
3. Is this consistently reproducible? 

Cheers

Brian

**Comment by narekam** [comment] 2017-01-19 13:34
1. I can't provide you this list unfortunately.
2. We included Intercom in our app's latest beta version, so it's not available for downloading.
3. Yes, it's 5 from 5.
**4. This is the key I think.** This happens only on iOS 8.  iOS 9 and 10 are both ok.

**Comment by bboyle18** [comment] 2017-01-19 13:44
Thanks @narekam 
The reason it would be great to see what 3rd party libs you are using is because we have found in the past that some of these interfere with Intercom's code by badly swizzling classes like UIView. So by knowing what libs you may be using would help diagnose the problem quicker.

Thanks

Brian

**Comment by narekam** [comment] 2017-01-19 14:03
Ya, I know Brian, but I not allowed to do that. Sorry for that. Please try to figure it out without this info.

Thanks in advance.

**Comment by bboyle18** [comment] 2017-01-20 17:27
Hi @narekam 👋 

We've released version [3.0.23](https://github.com/intercom/intercom-ios/releases/tag/3.0.23) which contains a fix for this. 🎉 

Thanks

Brian

**Closed by bboyle18** 2017-01-20 17:27 UTC

**Comment by jtreanor** [comment] 2017-01-24 14:55
There was an issue with the fix in 3.0.23 so we have released [3.0.24](https://github.com/intercom/intercom-ios/releases/tag/3.0.23) to fully resolve the issue.

James

**Comment by narekam** [comment] 2017-01-31 13:06
Thank you guys! 3.0.24 worked for us!
