### ISSUE TITLE
Open a push notification does not bring up the conversation detail screen

### ISSUE THREAD

**Issue by fabiomassimo** [intercom/intercom-ios#320] opened 2017-10-05 13:34 UTC
## Version info
  - Intercom for iOS version: 4.0.3
  - iOS version: 11.0

## Expected behavior

When opening the app from an Intercom push notification, the conversation detail opens automatically to let the user quickly reply.

## Actual behavior

A bubble containing the conversation message is presented on the bottom of the screen. If the user taps that bubble the conversation then opens as expected in the "Expected Behavior" criteria.

## Steps to reproduce

Before all: disable auto handling of push notification on intercom by setting the proper value in the Info.plist
 1. Send a message from intercom to an user
 2. Slide and open the push notification
 3. Identify the push notification payload with the `isIntercomPushNotification` and finally call `handleIntercomPushNotification` when appropriate.

## Logs

This is the payload we receive.

```
{
     "icm_cid" : THE_ICM_ID,
     "app_id": "THE_APP_ID",
      "aps" : {    
          "alert": "THE_MESSAGE",
          "sound" : "default"
      },
      "intercom_push_type": "notification"
}
```

**Comment by jtreanor** [comment] 2017-10-05 13:38
Hi @fabiomassimo,

Thanks for the write up. Where are you calling `handleIntercomPushNotification` from? Is it in `didReceiveRemoteNotification` or similar?

James

**Comment by serluca** [comment] 2017-10-05 13:45
Hi @jtreanor 

Luca here, @fabiomassimo colleague, we are calling `handleIntercomPushNotification ` from `userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:`

**Comment by jtreanor** [comment] 2017-10-05 13:53
Thanks @serluca,

Looks like there may be a bug here. We'll look into this and get back to you.

**Comment by jtreanor** [comment] 2017-10-05 15:06
Hi @fabiomassimo and @serluca,

I have run through the scenario you have described and I have been unable to reproduce the issue so far. Here are a few questions that may help track it down:

1. What is the value of `IntercomAutoIntegratePushNotifications` in your info.plist? If it is set to `NO`, try running through the issue while it is set to `YES`. This may help track down the cause.
2. Does the issue occur for all push notifications sent from Intercom or only while the app is coming from a backgrounded state/fresh launch.
3. If you breakpoint `userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:` can you see that it is being called?

Let me know if you have any questions about this.

Thanks,
James

**Comment by serluca** [comment] 2017-10-09 10:35
Hi @jtreanor 

Answering your questions:
1. The value of `IntercomAutoIntegratePushNotifications` is `NO` as we want to perform a login before showing the conversation. Setting that value to `YES` it works but we lose the ability to perform the login first.
2. The issue is for when the user opens the app from an intercom push notification, as we want from that action to open the proper intercom conversation window
3. Yes it gets called

Thanks,
Luca

**Comment by jtreanor** [comment] 2017-10-09 10:43
Thanks for taking the time to dig into this @serluca.

Your answer to 1 above suggests that `handleIntercomPushNotification` is not called directly from `userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:` but some time later after login is completed. Is this correct?

Intercom assumes that `handleIntercomPushNotification` is called directly when the push notification is received. This is because messages received later in the app lifecycle are handled by the real time messaging system. However, your use case here is valid and we should consider if there are changes we could make to support it.

**Comment by serluca** [comment] 2017-10-09 10:46
Hi @jtreanor 

Yes, it is correct.
It is now clear how it works, should I close this issue or will you take it from here as a feature request?

**Comment by jtreanor** [comment] 2017-10-09 10:58
We'll take it from here and evaluate if this should be considered an issue or feature request.

Thanks for your help @serluca and @fabiomassimo  😄

**Comment by bboyle18** [comment] 2017-11-27 16:19
Closing this issue as we are tracking this internally as a feature request.

Brian

**Closed by bboyle18** 2017-11-27 16:19 UTC
