### ISSUE TITLE
Running UI tests with intercom SDK causes infinite loop

### ISSUE THREAD

**Issue by frobichaud** [intercom/intercom-ios#120] opened 2016-02-15 00:37 UTC
Hi,
when running UI test with the Intercom lib, our CI server consumes 100% CPU and quickly jumps to 4GB of RAM usage. This only occurs if the intercom library is linked. It resolves when we remove it.
Our project is a built against XCode 7.2.1 and the library is imported through the Podfile.

**Comment by jtreanor** [comment] 2016-02-15 10:34
Hi @frobichaud,

Thanks for reporting this. Are you able to reproduce this locally (outside of CI). If so, could you use the Time Profile instrument to see if you can spot the culprit? Its possible that the issue isn't with Intercom directly, but with how Intercom and one of your dependencies interact.

What version of Intercom are you using?

**Comment by frobichaud** [comment] 2016-02-15 14:21
Hi @jtreanor, yes we are able to reproduce on our desktop when running tests. We're using version 2.3.19. I'll try to get some profiler data.

**Comment by jtreanor** [comment] 2016-02-19 16:39
Hi @frobichaud,

Any update on this? Feel free to email team@intercom.io and ask for James if you'd like me to help you dig into it.

**Comment by frobichaud** [comment] 2016-03-02 15:13
Hi @jtreanor,
I sent you some profiling details by email along our Podfile. Have you had the chance to try running UI tests with a sample project?

**Comment by frobichaud** [comment] 2016-03-14 21:19
hi @jtreanor, to work around this issue, we've removed the intercom dependency from the UI Tests target:
```
target "PetalMD" do
    all_pods()
    pod 'Intercom'
end
```

```
target "PetalMD Integration Tests" do
    all_pods()
end
```

You can close if you want, although there seems to be an underlying issue...

**Comment by jtreanor** [comment] 2016-03-15 09:45
Thanks @frobichaud,

I still have not been able to reproduce this in any project so I will close this for the time being.

**Closed by jtreanor** 2016-03-15 09:45 UTC
