### ISSUE TITLE
unreadConversationCount() returns incorrect value in some cases

### ISSUE THREAD

**Issue by ClaireDavis** [intercom/intercom-ios#242] opened 2017-03-21 15:12 UTC
## Version info
  - Intercom for iOS version: 3.1.2
  - iOS version: 8.0 +

## Expected behavior
Intercom.unreadConversationCount() should return the correct amount of unread conversations

## Actual behavior
Intercom.unreadConversationCount() will sometimes return one number, but after calling presentConversationList(), the list shows a different amount of unread messages.  In some cases, unreadConversationCount() will return 0, when in fact there is 1 unread shown in the conversation list.  In other cases, it will display 2 unread, but there are actually 10 unread messages.

## Steps to reproduce
 1. call Intercom.unreadConversationCount() and note the value returned
 2. call Intercom.presentConversationList() and observe number of unread messages
 3. There isn't always a mismatch, but sometimes these numbers do not match

**Comment by jtreanor** [comment] 2017-03-21 15:14
@ClaireDavis Immediately after launching your app `Intercom.unreadConversationCount()` will always return 0. This is because it hasn't yet received the response from Intercom.

For this reason, you should observe `IntercomUnreadConversationCountDidChangeNotification` and only display the count in your UI when this fires.

**Comment by ClaireDavis** [comment] 2017-03-21 15:18
@jtreanor  thanks for the quick response - this isn't presented in my app until well after the initial call to intercom is made, and I am observing IntercomUnreadConversationCountDidChangeNotification which is never fired to update the number of messages

**Comment by jtreanor** [comment] 2017-03-21 15:20
Just to be clear, when your app is launched `IntercomUnreadConversationCountDidChangeNotification` is never fired. Is this correct even if the user has unread conversations?

**Comment by ClaireDavis** [comment] 2017-03-21 15:24
Sorry, it's being fired, but `Intercom.unreadConversationCount()` is still returning an incorrect value after it is fired.  So in this case, after `IntercomUnreadConversationCountDidChangeNotification` is received, `Intercom.unreadConversationCount()` still returns 0 even though I have 1 unread message.  In other cases, it might return 2 even though I have ~10 unread messages.

**Comment by jtreanor** [comment] 2017-03-21 15:32
Thanks for the detail @ClaireDavis,

We'll look into this and let you know what we find.

**Comment by lucianocn** [comment] 2017-04-07 05:15
@jtreanor What about if the app is returning from background? The count can changed, but ``IntercomUnreadConversationCountDidChangeNotification`` isn't fired and also ``unreadConversationCount`` always return the wrong value 0.

#248

**Comment by ClaireDavis** [comment] 2017-04-18 14:35
@jtreanor  any updates here?

**Comment by jtreanor** [comment] 2017-04-18 14:53
@ClaireDavis We fixed an issue in [3.1.5](https://github.com/intercom/intercom-ios/releases/3.1.5) which could lead to Intercom not successfully loading unread conversations.

Could you try it out to see if it resolves your issue?

**Comment by lucianocn** [comment] 2017-04-19 00:58
@jtreanor I tried 3.1.5 by the it's not fixed for me ;(

**Comment by ClaireDavis** [comment] 2017-04-19 13:24
I'm still experiencing the same issue as well

**Comment by jtreanor** [comment] 2017-04-19 14:06
Thanks for letting me know @ClaireDavis and @lucianocn

**Comment by ugenlik** [comment] 2017-06-20 19:05
Same here, cocoapods `Using Intercom (3.2.5)` `Intercom.unreadConversationCount()` always returns 0.

**Comment by jtreanor** [comment] 2017-06-20 23:10
Hi @ugenlik,

Have you tried my suggestion from the comment above:

> Immediately after launching your app Intercom.unreadConversationCount() will always return 0. This is because it hasn't yet received the response from Intercom.

> For this reason, you should observe IntercomUnreadConversationCountDidChangeNotification and only display the count in your UI when this fires.

**Comment by jtreanor** [comment] 2017-06-21 00:05
@ClaireDavis @lucianocn I have tried again to reproduce this issue but unfortunately I can't so far. Is there any more detail about your specific use cases that may be helpful?

**Comment by bboyle18** [comment] 2017-09-11 15:44
Hi @ClaireDavis @ugenlik @lucianocn 👋 

We have spent some time recently trying to recreate this issue in a variety of scenarios but have been unsuccessful. 😞 

We'd love to get to the bottom of this issue thought.
Would it be possible for you guys to send us sample project that recreates the issue? 🙏 

Cheers

Brian

**Comment by bboyle18** [comment] 2017-09-14 10:14
I'm going to close this issue as we cannot reproduce it.
@ClaireDavis @ugenlik @lucianocn please feel free to re-open if you can provide us with a sample project to reproduce the issue.

Brian

**Closed by bboyle18** 2017-09-14 10:14 UTC
