### ISSUE TITLE
Crash in PodIntercom_IntercomBatchUpdateOperation

### ISSUE THREAD

**Issue by gransell** [intercom/intercom-ios#72] opened 2015-06-09 09:58 UTC
Hi

We recently updated to 2.2.3 and have now started noticing a few crashes in PodIntercom_IntercomBatchUpdateOperation. Seems to be some insertions/deletions in a collection view that are failing.

I have uploaded the crash log here: https://gist.github.com/gransell/bf46a8f4a53b9b974c2f

Unfortunately don't have more information than this.

**Comment by jtreanor** [comment] 2015-06-09 13:49
Thanks for the report @gransell. I will follow up in Intercom to discuss this further.

**Comment by gransell** [comment] 2015-06-09 14:40
Unfortunately no. This has come in through external crash reports from end users so we don't really have any more information.

**Comment by jtreanor** [comment] 2015-06-09 19:12
Ok, thanks @gransell. I appreciate you sending this in: I will work on reproducing this locally.

**Comment by gransell** [comment] 2015-06-10 07:03
No problems. I'll update this issue if I find anything.

**Comment by gransell** [comment] 2015-08-24 09:02
Hi

Any update on this? We are seeing more and more of this in production. Any information that you need from us?

**Comment by adamkmccarthy** [comment] 2015-08-24 09:06
Thanks @gransell, in terms of volume how many of these are you seeing? (feel free to ping me in Intercom if you'd prefer not to discuss that here). We're chasing it down but haven't found the cause just yet. Some additional raw crash logs would be great if you had them to hand. Thanks, Adam.

**Comment by gransell** [comment] 2015-08-24 09:21
We have been seeing everything between 0 and 5 crashes per week during summer. I can dig up some more crash logs. Whats the best way to ping you in intercom? Perhaps easier to send over all the crash logs there.

**Comment by adamkmccarthy** [comment] 2015-08-24 09:22
Thanks @gransell. Ping team [at] intercom.io and mention @jtreanor and myself and we'll sift through them. Thanks a million!

**Comment by amburke** [comment] 2015-09-24 16:53
Another report of this from a customer: 
https://intercomrades.intercom.io/a/apps/tx2p130c/inbox/alex.burke@intercom.io/conversations/1173907826

**Comment by jtreanor** [comment] 2015-10-08 15:34
Although this is proving to be very difficult to track down, we have made some changes in 2.3.11 that I am hopeful may mitigate this issue.

**Comment by gransell** [comment] 2015-10-09 06:56
Thanks @jtreanor. We will give it a try and report back.

**Comment by jtreanor** [comment] 2015-11-13 16:58
This has been fixed in 2.3.12.

**Closed by jtreanor** 2015-11-13 16:58 UTC
