### ISSUE TITLE
Push notification payload 

### ISSUE THREAD

**Issue by abreckler** [intercom/intercom-ios#144] opened 2016-07-20 18:48 UTC
We are not able to properly send users to our 'single post view' routing via push notifications sent from Intercom.

## Version info
  - Intercom for iOS version:  **2.3.21**
  - iOS version: **9.3.2**

## Expected behavior

Clicking push notification opens app and sends you to a single post view.

## Actual behavior

Clicking push notification opens app, but the single post view is not triggered.

## Steps to reproduce
 1.  Install Blink http://go.blink.am/invc
 2. Click 'blink.am://p/wx2cs7' in a text message top test uri sending to single post.
 3. Same uri as a intercom push notification doesn't bring you to the single post.

## Logs

1. Can you share the CFBundleURLSchemes section of your info.plist?
<array> 
<string>blinkam</string> 
<string>fb1640891429483923</string> 
<string>com.googleusercontent.apps</string> 
<string>am.blink.blink</string> 
</array>

2. It would also be worth calling [Intercom enableLogging:YES] and seeing if there are any logs from Intercom when the push is opened.

debugger shows this [Intercom] ERROR - Tried to mark a conversation as read but there was a network error - Request failed: not found (404)

3. Do you use any other push provider in your app? e.g. UrbanAirship, Parse, Localytics?
None

We don't use any other push service now

**Comment by jtreanor** [comment] 2016-07-21 18:03
Hi @abreckler,

We have just released [3.0.0](https://github.com/intercom/intercom-ios/releases/tag/3.0.0) which includes improvements to how push notifications work.
Could you try out this version and let us know how you get on?

**Comment by abreckler** [comment] 2016-07-21 18:38
hi @jtreanor we are actually using pod 'Intercom', '~> 3.0.0-beta5', has there been an update to that functionality since then?

**Comment by jtreanor** [comment] 2016-07-22 08:36
Thanks @abreckler,

There were some changes so it would be worth trying out the new version.

One additional question which may help is can you send in app messages to this user while they have the app open? It's possible the issue is not with push itself.

**Comment by jtreanor** [comment] 2016-07-22 13:59
We have just released [3.0.1](https://github.com/intercom/intercom-ios/releases/tag/3.0.1) which includes more improvements to push notifications.
Let me know when you have a chance to test your app out with the latest version.

**Comment by jtreanor** [comment] 2016-07-25 17:44
Any updates here @abreckler?

**Comment by abreckler** [comment] 2016-07-28 00:23
@jtreanor still no luck :(

**Comment by jtreanor** [comment] 2016-07-28 08:45
@abreckler Thanks for checking.

We have just released [3.0.4](https://github.com/intercom/intercom-ios/releases/tag/3.0.4) which includes several more improvements to push notifications.

**Comment by jtreanor** [comment] 2016-07-29 12:33
I have tested this extensively and I am confident that this is now fixed in 3.0.4. Feel free to reopen if you see this again.

**Closed by jtreanor** 2016-07-29 12:33 UTC

**Comment by abreckler** [comment] 2016-08-01 16:37
@jtreanor no luck :(

**Comment by jtreanor** [comment] 2016-08-01 18:38
@abreckler thanks for letting me know, I'll take another look into your specific issue.

**Comment by jtreanor** [comment] 2016-08-02 16:46
@abreckler Could you try this once more with 3.0.7?
I spent some time digging today but I haven't been able to reproduce the issue locally.

**Comment by nickkuh** [comment] 2016-08-04 15:48
Hi @jtreanor - started integrating Intercom into a client's iOS app today. 

I'm using Intercom to send manual push notifications that direct the user to a screen in the app based on custom IOS URI. It works well when the user taps on the push when the app is in the background. However, when the app is in the foreground neither of the 2 application delegate callbacks seem to get fired

`public func application(application: UIApplication, didReceiveRemoteNotification userInfo: [NSObject : AnyObject])`

or 

`public func application(application: UIApplication, didReceiveRemoteNotification userInfo: [NSObject : AnyObject], fetchCompletionHandler completionHandler: (UIBackgroundFetchResult) -> Void)`

Is that the same as this issue above? Using v3.0.7 in a Swift iOS project.

**Comment by nickkuh** [comment] 2016-08-04 15:49
Also - why can't your system work with dev pem certificates too? It makes debugging really really slow 👎

**Comment by jtreanor** [comment] 2016-08-04 15:56
Hi @nickkuh,

It is actually correct that `didReceiveRemoteNotification:` and `didReceiveRemoteNotification: fetchCompletionHandler :` don't get called for Intercom push, since we handle it internally.

Does does the app's [`application:openURL:options:`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/#//apple_ref/occ/intfm/UIApplicationDelegate/application:openURL:options:) method get called when the push is opened?

I hear you about the dev push 👍

**Comment by nickkuh** [comment] 2016-08-04 16:02
@jtreanor thanks for the super quick reply.

When the app is in the background and the push comes through then yes, 'application:openURL:options:' gets called if I tap on the push notification. Cool.

However, when the app is in the foreground and I send the same push nothing gets called. Is there a hook I can tap into for this scenario?

**Comment by nickkuh** [comment] 2016-08-04 16:31
@jtreanor - ok, thanks. The message doesn't display via the Intercom SDK either when the app is in the foreground. Feels like the message never got sent/received. 

Thanks

Nick

**Comment by jtreanor** [comment] 2016-08-04 16:36
@nickkuh Yeah I understand why this is confusing, but push messages aren't currently get displayed when the app is in the foreground.
If you want to receive messages when in the foreground you can send an in app message (chat, note etc.).

**Comment by nickkuh** [comment] 2016-08-04 16:37
Sure - but then I can't send any custom data with the message to get the app to jump to the content I'm referencing.

**Comment by jtreanor** [comment] 2016-08-04 16:47
You can send a button or link with a URI for the app and it will go there when pressed.
