### ISSUE TITLE
Composer message is not clearing on close

### ISSUE THREAD

**Issue by MaxAdamyan** [intercom/intercom-ios#348] opened 2017-12-05 13:08 UTC
## Version info
  - Intercom for iOS version: 4.1.3
  - iOS version: 11.1

## Expected behavior
When user enters text in message composer but does not send it (closes Intercom window), the next time he opens message composer the text field is empty

## Actual behavior
When user enters text in message composer but does not send it (closes Intercom window), the next time he opens message composer the text field is pre-populated with text he entered in the first place

## Steps to reproduce
 1.  Open Intercom Message Composer
 2.  Write something
 3.  Close Intercom window w/o sending
 4.  Open Intercom Message Composer again

## P.S.
This issue does not allow me to PresentComposer with initial message because there is already text in composer (my initial message is ignored)

**Comment by bboyle18** [comment] 2017-12-05 13:13
Hi @MaxAdamyan 👋 

Thanks for reporting this.
Your first point about the composer being pre-populated with the same text if you don't send the message...this is by design.
However, you said that you can't then pre-populate the composer with a pre-defined message....this is a bug. We'll fix this and update you here when its released.

Thanks

Brian

**Comment by MaxAdamyan** [comment] 2017-12-05 14:11
Hi @bboyle18 
Thanks for quick response 👍 

When can we expect the release??

Thanks,
    Max

**Comment by bboyle18** [comment] 2017-12-05 14:14
We aim to do a release every week, so hopefully sometime later this week.

**Comment by bboyle18** [comment] 2017-12-11 20:40
Fixed in [Release 4.1.5](https://github.com/intercom/intercom-ios/releases/tag/4.1.5)
Thanks for reporting.

**Closed by bboyle18** 2017-12-11 20:40 UTC
Labels: close-on-next-release
