### ISSUE TITLE
Opening the specific message for a push notification that the user tapped

### ISSUE THREAD

**Issue by kylejm** [intercom/intercom-ios#308] opened 2017-09-04 10:56 UTC
My colleague and I have been trying to figure out the best UX for a user receiving a push notification for an Intercom message. We agree that the best thing to do would be to present the specific message that the notification is for, but this doesn't seem to be possible using the Intercom APIs.

We looked at [docs here](https://developers.intercom.com/docs/ios-push-notifications#section-step-6-handling-intercom-push-notifications) and found implementing Intercom's push notification handling just presents (what I would call) the Conversation List.

Could we make a feature request or ask for advice on opening specific conversations from push notifications?

**Comment by bboyle18** [comment] 2017-09-04 11:05
Hi @kylejm 👋 

Intercom automatically handles the opening of a specific conversation when you tap on a push notification.
Are you using Intercom's [automatic handling of push notifications](https://developers.intercom.com/docs/ios-push-notifications#section-step-6-handling-intercom-push-notifications) or are you choosing to handle push notifications manually?

Cheers

Brian

**Comment by fabiomassimo** [comment] 2017-09-05 13:30
Hi @bboyle18 ,
I'm @kylejm's colleague working more closely on this issue. Thank you for jumping on the issue so fast.

Our app needs to handle push notifications manually after the user goes through a login process.
We have adjusted the `Info.plist` as required and using `Intercom.handlePushNotification(userInfo)` to forward the push notification payload once we have granted the access to the user, although this does not open the Intercom interface right on the message that user tap/swiped from the push notification but rather present the Intercom interface with the list of all conversations for that user.
Is this the expected behaviour? 

While "speaking" I'm also updating to latest version of `intercom-ios` to make sure we are not missing any last fix you guys have been working on.

**Comment by bboyle18** [comment] 2017-09-05 14:44
This make sense @fabiomassimo, thanks for clarifying.
What you have described is expected behaviour. We currently don't provide any way to open a specific message when handling push notifications manually.

Is there a reason you can't use the automatic push notification handling?

Cheers

Brian

**Comment by fabiomassimo** [comment] 2017-09-05 14:51
The reason why we can not handle the push notification automatically is because when the user is opening the app, because of tap/swiping a push notification message, we first have to authenticate the user and last let him access the push notification's conversation.

In my understanding, and empirical testing, the swizzling of the `UIApplicationDelegate` callback for when a push notification is received (which enables the automatic push notification handling behaviour), makes it impossible to not let intercom open the notification message prior to user's authentication via our login screen.

I hope this makes sense to you.

Cheers.

Fabio.

**Comment by bboyle18** [comment] 2017-09-05 15:07
@fabiomassimo Having looked at our code a little closer, it should open the specific conversation when you call `Intercom.handlePushNotification(userInfo)`. So please dismiss my earlier comment!

If it is not opening the specific message for you, before you call `Intercom.handlePushNotification(userInfo)`, can you please print the contents of `userInfo` to the console and send it to us please?
I should expect to see a property `icm_cid` which is the ID of the message.

Thanks

**Comment by fabiomassimo** [comment] 2017-09-05 15:23
Thank you @bboyle18 for having the time to dive into this closer.

I'll come back to you as soon as I'll have your question answered.

Cheers.

**Comment by bboyle18** [comment] 2017-09-08 10:06
Hi @fabiomassimo 👋 
Any update you can provide us on this issue?

Thanks

Brian

**Comment by fabiomassimo** [comment] 2017-09-11 07:11
Hi @bboyle18 ,
the `Intercom.handlePushNotification` now works as expected. Not sure if the issue was temporary or matter of intercom-ios version. Please close this issue. In case it occurs again I'll ask to reopen it with the information you asked me to provide.

Thanks.

**Closed** 2017-09-11 08:50 UTC

**Comment by bboyle18** [comment] 2017-09-11 09:14
Thanks @fabiomassimo

**Comment by fabiomassimo** [comment] 2017-10-04 14:12
Sorry to bring this up again but we are experiencing the case where when we call `Intercom.handlePushNotification` with the user info from the push notification the user just interacted with, it shows the conversation message in the "_Intercom bubble_" but does not automatically present the _Intercom Messenger_ with the conversation already open.

Is this the expected behavior?
