### ISSUE TITLE
Crash in io.intercom.PodIntercom_SRWebSocket.NetworkThread

### ISSUE THREAD

**Issue by mhemmings** [intercom/intercom-ios#127] opened 2016-03-16 16:32 UTC
Crash reported on iOS 9.2.1 - iPhone 6 Plus
Intercom 2.3.19

See report here: http://crashes.to/s/82a8aebe478

````
Thread : Crashed: io.intercom.PodIntercom_SRWebSocket.NetworkThread
0  libobjc.A.dylib                0x1826117c8 weak_register_no_lock + 56
1  libobjc.A.dylib                0x182618688 objc_initWeak + 224
2  FitGurus                       0x1002a737c -[PodIntercom_SRWebSocket stream:handleEvent:] + 4298404732
3  CoreFoundation                 0x182ee6644 _signalEventSync + 192
4  CoreFoundation                 0x182ee6560 _cfstream_shared_signalEventSync + 444
5  CoreFoundation                 0x182f48efc __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
6  CoreFoundation                 0x182f48990 __CFRunLoopDoSources0 + 540
7  CoreFoundation                 0x182f46690 __CFRunLoopRun + 724
8  CoreFoundation                 0x182e75680 CFRunLoopRunSpecific + 384
9  Foundation                     0x18386d21c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 308
10 FitGurus                       0x1002a861c -[PodIntercom__SRRunLoopThread main] + 4298409500
11 Foundation                     0x183953c40 __NSThread__start__ + 1000
12 libsystem_pthread.dylib        0x182bfbb28 _pthread_body + 156
13 libsystem_pthread.dylib        0x182bfba8c _pthread_body + 154
14 libsystem_pthread.dylib        0x182bf9028 thread_start + 4
````

**Comment by ronocod** [comment] 2016-03-16 17:09
Hi @mhemmings,

Thanks for reporting this, it looks like an issue with SocketRocket, possibly related to #124 and #125 . We're looking into fixing these, and we'll let you know here whenever we have an update.

**Comment by DaleCantwell** [comment] 2016-04-14 09:13
Going to close this one as a duplicate of #124 
Thanks for providing us with a crash log.

**Closed by DaleCantwell** 2016-04-14 09:13 UTC
Labels: duplicate
