### ISSUE TITLE
AFURLSessionManagerTaskDelegate

### ISSUE THREAD

**Issue by ryanjm** [intercom/intercom-ios#186] opened 2016-10-18 16:18 UTC
## Version info
- Intercom for iOS version: 3.0.14
- iOS version: 10.0.2
## Expected behavior

App not to crash.
## Actual behavior

App crashes.
## Steps to reproduce

Unknown
## Logs

[Crashlytics](http://crashes.to/s/64af35aae1b)

Everything in the logs is pointing to an issue with `-[PodIntercom_AFURLSessionManagerTaskDelegate observeValueForKeyPath:ofObject:change:context:]`. During the time that this is happening I believe the app has it's own progress bar / NSProgress notifications being sent. Would that interfere with anything happening in the intercom library?

This doesn't happen every time (thus there are no steps to take) but it does happen every once in awhile.

Please let me know if there is anything else I can help provide.

**Comment by bboyle18** [comment] 2016-10-18 16:50
Hi @ryanjm 👋

Thanks for reporting this. 
You're progress bar shouldn't interfere with Intercom's code but it would be good if you could share some more info on what your app is doing at this point. Can you provide us with notifications that are being fired at this time?
It would also be great if you could provide the full crashlytics stack trace. 

Thanks

Brian

**Comment by ryanjm** [comment] 2016-10-18 18:49
Thanks Brain,

This doesn't happen in a repeatable manner so I'm not sure what notifications are being fired at this particular time. And the stack trace doesn't show any sections of my code running so I can't even provide notifications based on that.

How can I share the full crashlytics stack trace? I thought the link above provided that.

**Comment by jtreanor** [comment] 2016-10-24 13:20
Hi @ryanjm,

I have done some digging to see what is causing this.

For a little background, Intercom uses its own copy of AFNetworking which is why you see classes like `PodIntercom_AFURLSessionManagerTaskDelegate` in the log. We do this so that it doesn't interfere at all with the host app.

The cause of this issue seems to be inconsistencies with how `NSURLSessionTask` behaves under KVO. It was fixed in https://github.com/AFNetworking/AFNetworking/pull/3607. Unfortunately these changes have not yet been released by the AFNetworking team. I'm not aware when this release is planned.

If you wish you can install the latest AFNetworking from Github that includes this change:
```
pod 'AFNetworking', :git => 'git@github.com:AFNetworking/AFNetworking.git'
```

**Comment by ryanjm** [comment] 2016-10-24 14:42
@jtreanor Thanks for the update. I do use AFNetworking in my project so I'll need to review their changes and make sure I can safely upgrade to the latest version. 

But this does being up an interesting question. Since Intercom includes its own copy of AFNetworking, what happens when the host app also includes AFNetworking?

1. Are two copies of AFNetworking includes, thus increasing the overall size of the project (not that I'm too worried about this). 
2. You mention I could update it for my project, so then does Intercom check the two versions of AFNetworking and use one over the other or will it only use it's own copy? That is, will updating my project's version really fix the issue for Intercom when it is looking to use `PodIntercom_AFURLSessionManagerTaskDelegate`?

**Comment by jtreanor** [comment] 2016-10-24 15:14
1. The short answer here is yes. However, the impact on the AppStore binary size caused by this is negligible and in the order of Kilobytes.

2. No, Intercom will continue to use its own copy of AFNetworking. I can't be sure if it will or not. It is possible that the underlying issue will stop if the two copies don't both use KVO, but that is a guess.
I will update Intercom to use the fix as soon as it is released. Unfortunately its not possible for us to include the version from Github due to how our Framework is built. I'll follow up with the AFNetworking team to see if they have a rough timeline for release.

**Comment by jtreanor** [comment] 2016-10-25 14:11
I have done some more investigation here and have decided a path forward: future versions of Intercom will use `AFURLSessionManager`. This means that bugs such as this will not be possible.

I will keep you updated on the release of this change. It will most likely be in the next week.

**Comment by jtreanor** [comment] 2016-11-02 12:00
The changes I described above are now included in [https://github.com/intercom/intercom-ios/releases/tag/3.0.18](3.0.18).

Thanks again for reporting this 😄

**Closed by jtreanor** 2016-11-02 12:00 UTC

**Comment by ryanjm** [comment] 2016-11-04 16:52
Thanks for the update @jtreanor! I'll get that updated shortly.
