### ISSUE TITLE
New Intercom Messenger key window issue

### ISSUE THREAD

**Issue by nu-steve** [intercom/intercom-ios#160] opened 2016-08-05 09:51 UTC
## Version info
  - Intercom for iOS version: 3.0.7
  - iOS version: 9.3

## Expected behavior
After closing messenger window, all previous functions of the app should still work as before.
## Actual behavior
Navigation bar buttons stop responding until app has been restarted.
## Steps to reproduce
 1. Add button to navigation bar
 2. Open Intercom Messenger
 3. Press Navigation bar button

## Logs
N/A

**Comment by jtreanor** [comment] 2016-08-05 10:00
Hi @nu-steve,

Can you try out the latest version (3.0.8) and let me know if there are any changes?

**Comment by nu-steve** [comment] 2016-08-05 11:26
Hi @jtreanor 

It seems the problem is with the rootViewController. After some debugging, it seems our sidebar is also using the [UIApplication sharedApplication].keyWindow.rootViewController to display the sidebar. If I open our sidebar several times, the value of the rootView controller doesn't change, but after opening Intercom and reopening the sidebar, the value of the rootViewController changes.

You can see the method that we are running below.

```
- (void)showAnimated:(BOOL)animated
{
    UIViewController *controller = [UIApplication sharedApplication].keyWindow.rootViewController;
    
    while (controller.presentedViewController != nil) {
        controller = controller.presentedViewController;
    }
    [self showInViewController:controller animated:animated];
}
```

Any method I run that uses the keyWindow.rootViewController doesn't work after opening Messenger. It just happens that two of our NavigationBar buttons use the rootViewController to display a full screen popup.

Any ideas?

**Comment by nu-steve** [comment] 2016-08-05 11:54
@jtreanor On another note, I wrote the incorrect OS version in my first post. Our target OS is iOS 8.0+

The device I was using was iOS 9.3. Sorry for the confusion there.

**Comment by jtreanor** [comment] 2016-08-05 12:20
Thanks for digging into this @nu-steve. Your assessment of the cause sound correct.

When Intercom present's the Messenger, it becomes the key window. This is necessary in order for user interaction to work correctly.

The issue here is that the sidebar component assumes `[UIApplication sharedApplication].keyWindow` never changes, which is not a safe assumption to make in any app. It should be using `self.view.window` or similar.

What is the sidebar component that you are using?

**Comment by nu-steve** [comment] 2016-08-05 13:32
No prob @jtreanor. We are using [CDRTranslucentSideBar](https://github.com/chidori-app/CDRTranslucentSideBar)  

Any ideas how to resolve this?

**Comment by jtreanor** [comment] 2016-08-05 14:50
@nu-steve I've done a little more digging here and I'm confident this should be straightforward to resolve.

Can you clarify you replace usages of `[UIApplication sharedApplication].keyWindow` in your own app with `self.view.window` and let me know if they work correctly?

I still don't quite understand how this would effect your app. Once the Intercom Messenger window closes, your app's window should resume being the key window.

**Comment by nu-steve** [comment] 2016-08-05 15:29
@jtreanor that's what I also find strange.

We didn't have any issues with the old messenger, but as soon as we updated the issue was very clear. I've tried changing all instances of `[UIApplication sharedApplication].keyWindow` to `self.view.window` but then the sidebar never appears, even before opening Intercom.

Did previous versions of Intercom also use `[UIApplication sharedApplication].keyWindow`?

I'd really like to resolve this issue ASAP so we can push out our most recent app update.

**Comment by jtreanor** [comment] 2016-08-05 15:36
@nu-steve Yes previous versions on Intercom had this same behaviour of using key window. Do you have usages of `[UIApplication sharedApplication].keyWindow` in your app outside of the sidebar?

**Comment by nu-steve** [comment] 2016-08-05 15:41
@jtreanor We use `[UIApplication sharedApplication].keyWindow` in a few places and have never had any issues before. As I mentioned before, after closing Intercom the rootViewController does not change back to the original. I think that's what's causing the issue.

**Comment by jtreanor** [comment] 2016-08-05 15:46
@nu-steve Can you verify that your app's window does not become key when Intercom closes.
A log like this when the button is pressed should work:
```
NSLog(@"App has key window: %d", [UIApplication sharedApplication].windows[0].isKeyWindow);
```

I'll investigate if there are any cases where the app may not be handed back the key window.

**Comment by nu-steve** [comment] 2016-08-05 15:58
Just tested and prior to opening Intercom the key window is 0. After opening, it becomes 1. Would it help if I gave you access to our source code to debug? If so, let me know your email address and I'll send it over.

**Comment by jtreanor** [comment] 2016-08-05 15:59
@nu-steve That is interesting and likely the cause. Sure, my email is james@intercom.io.

**Comment by nu-steve** [comment] 2016-08-05 16:05
@jtreanor Great! Just uploading the project to our CDN now and I'll email you over a link. Bear in mind it will be a link to our Chinese server so maybe not the fastest download speed for you in the US.

**Comment by jtreanor** [comment] 2016-08-08 15:34
This is now fixed in [3.0.9](https://github.com/intercom/intercom-ios/releases/tag/3.0.9) 🎉 

Thanks again for your help fixing this @nu-steve.

Some context for anyone who may be reading: the issue was that for some apps with multiple UIWindows, when the Intercom Messenger is closed the wrong window from the host app may be made the new key window. This change ensures the host app's primary window is made key.

**Closed by jtreanor** 2016-08-08 15:34 UTC

**Comment by jianqingyu** [comment] 2017-10-26 03:09
ios 11  The collapse in  [parentViewController.view addSubview:self.view];

**Comment by jtreanor** [comment] 2017-10-26 10:27
Hi @jianqingyu,

Can you clarify what you mean here? Are you having an issue with Intercom in your iOS app?

James
