### ISSUE TITLE
IntercomUnreadConversationCountDidChange not fired when setInAppMessagesVisible=false

### ISSUE THREAD

**Issue by philippb** [intercom/intercom-ios#298] opened 2017-08-24 17:27 UTC
I'm experiencing a problem where `NSNotification.Name.IntercomUnreadConversationCountDidChange` Notification is not dispatched when I set `Intercom.setInAppMessagesVisible(false)`.

## Version info
  - Intercom for iOS version: 3.2.12
  - iOS version: 10.3.1 (Simulator)

## Expected behavior
I will always receive `.IntercomUnreadConversationCountDidChange` notifications when there is a new message coming in, regardless of the `inAppMessagesVisibility` flag.

## Actual behavior
I only receive notification about new unread messages when `Intercom.inAppMessagesVisibility` is set to `true`. 

## Steps to reproduce
 1. Create example app that register for notifications
 2. Set `Intercom.setInAppMessagesVisibility(true)`
 3. Send message from the web interface and watch `NSNotification` messages come in.
 4. Change `Intercom.setInAppMessagesVisibility(false)`
 5. Send another message from the website, and observe the the notification is not coming.

**Comment by bboyle18** [comment] 2017-08-25 13:32
Hi @philippb 👋 
Thanks for getting in touch.
We've tried to reproduce this issue but were unable to. 
Would you be able to share this sample project with us so that we can reproduce it please?

Thanks!

Brian

**Comment by nharbo** [comment] 2017-08-28 11:50
I have the same issue! Did you ever find a solution @philippb  ?

**Comment by bboyle18** [comment] 2017-08-28 16:05
@nharbo Do you have a sample project you could share with us? As mentioned in my comment above, we are unable to reproduce the issue.
Thanks!

Brian

**Comment by nharbo** [comment] 2017-08-29 08:31
Unfortunately I haven't got a sample project - I just tried implementing it in my "live" project. Anyway, I went for your build-in solution with the "message-bubble" popping up when a new message is received :) That works for now. But please let me know, if you find a solution to this :) It made it impossible for me to add a badge in my tapbar when a new message is received :)

**Comment by bboyle18** [comment] 2017-09-01 08:34
Hi @philippb 👋 
Was wondering if you have an example project you can share with us to help us recreate and fix this issue?

Thanks

Brian

**Comment by bboyle18** [comment] 2017-09-11 15:45
Hi @philippb 
I'm going to close this issue for now as I've been unable to recreate it.
If you can provide us with a small sample project that recreates the issue I'll reopen and investigate.

Thanks!

Brian

**Closed by bboyle18** 2017-09-11 15:45 UTC
